[build]
builder = "NIXPACKS"
buildCommand = "npm install"
watchPatterns = ["server/**/*.js", "**/*.json"]

[deploy]
startCommand = "npm run server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "wiki-ai-server"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
